### ISSUE TITLE
Meetings AP : difference between diagram and table description on vcard:hasLocality - mix between session and sitting

### ISSUE THREAD

**Issue by tfrancart** [europarl/eli-ep#23]
The diagram at https://europarl.github.io/eli-ep/dsd/meetings/ indicates that vcard:hasLocality is expressed on the plenary sitting and on the foreseen activity. But the table description of the model indicates it is expressed on the plenary session. The API output example gives it on the plenary sitting.

BTW, I think there is a mismatch between the name of the shape and its target; the shape "plenary session" seems to apply to plenary sittings, from what I read from the SPARQL query:

![image](https://github.com/europarl/open-data-beta-testing/assets/2728945/1860b308-1c62-4d9a-bc2a-5244f116f505)

Strange, no ?
@vanessa-ep

**Comment by vanessa-ep** [comment]
The ttl files (#24) and the html files (#21 #22 ) were fixed with the correct labels. I will close the issue.
